; Ohnrscript LLVM IR Backend
; generated by generator-llvm.ohn

declare ptr @ohn_alloc_f32(i32)
declare void @ohn_free(ptr)

@ohn_uuid_initialized = global i1 0
@ohn_uuid_exports = global ptr null
@crypto = global i32 0
@POOL_SIZE = global i32 0
@pool = global i32 0
@poolOffset = global i32 0
@outBuffer = global i32 0
@hexLookup = global i32 0
@HYPHEN = global i32 0
@rawBuffer = global i32 0

define ptr @__get_module_exports_ohn_uuid() {
entry:
  %init_flag = load i1, ptr @ohn_uuid_initialized
  br i1 %init_flag, label %return_block, label %init_block
init_block:
  store i1 1, ptr @ohn_uuid_initialized
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t0 = add i32 0, 0
  store i32 %t0, ptr @crypto
  %t1 = add i32 0, 65536
  store i32 %t1, ptr @POOL_SIZE
  %t2 = load i32, ptr @POOL_SIZE
  %t3 = call ptr @ohn_alloc_f32(i32 %t%t2)
  store i32 %t3, ptr @pool
  %t4 = load i32, ptr @POOL_SIZE
  store i32 %t4, ptr @poolOffset
  %t5 = add i32 0, 36
  %t6 = call ptr @ohn_alloc_f32(i32 %t%t5)
  store i32 %t6, ptr @outBuffer
  ; UNSUPPORTED node type: 0xe
  %t7 = add i32 0, 0
  %t8 = call ptr @ohn_alloc_f32(i32 %t%t7)
  store i32 %t8, ptr @hexLookup
  %t9 = add i32 0, 45
  store i32 %t9, ptr @HYPHEN
  %t10 = load i32, ptr @HYPHEN
  %t11 = load ptr, ptr @outBuffer
  %t12 = add i32 0, 8
  %t13 = getelementptr i32, ptr %t11, i32 %t12
  store i32 %t10, ptr %t13
  %t14 = load i32, ptr @HYPHEN
  %t15 = load ptr, ptr @outBuffer
  %t16 = add i32 0, 13
  %t17 = getelementptr i32, ptr %t15, i32 %t16
  store i32 %t14, ptr %t17
  %t18 = load i32, ptr @HYPHEN
  %t19 = load ptr, ptr @outBuffer
  %t20 = add i32 0, 18
  %t21 = getelementptr i32, ptr %t19, i32 %t20
  store i32 %t18, ptr %t21
  %t22 = load i32, ptr @HYPHEN
  %t23 = load ptr, ptr @outBuffer
  %t24 = add i32 0, 23
  %t25 = getelementptr i32, ptr %t23, i32 %t24
  store i32 %t22, ptr %t25
  %t26 = add i32 0, 16
  %t27 = call ptr @ohn_alloc_f32(i32 %t%t26)
  store i32 %t27, ptr @rawBuffer
  ; (module.exports skipped — handled by lazy gett  store ptr null, ptr @ohn_uuid_exports
  br label %return_block
return_block:
  %exports_val = load ptr, ptr @ohn_uuid_exports
  ret ptr %exports_val
}

define i32 @fillEntropy() {
entry:
  %t0 = load i32, ptr @poolOffset
  %t1 = load i32, ptr @POOL_SIZE
  %t2 = icmp sge i32 %t0, %t1
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %then.0, label %merge.0
then.0:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t5 = add i32 0, 0
  %t6 = add i32 0, 0
  store i32 %t6, ptr @poolOffset
  br label %merge.0
merge.0:
  ret i32 0
}

define i32 @generateUUIDv4() {
entry:
  %outIndex = alloca i32
  %i = alloca i32
  %_byte = alloca i32
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t0 = add i32 0, 0
  %t1 = add i32 0, 0
  store i32 %t1, ptr %outIndex
  %t2 = add i32 0, 0
  store i32 %t2, ptr %i
  br label %for.0
for.0:
  %t3 = load i32, ptr %i
  %t4 = add i32 0, 16
  %t5 = icmp slt i32 %t3, %t4
  %t6 = zext i1 %t5 to i32
  %t7 = icmp ne i32 %t6, 0
  br i1 %t7, label %forbody.0, label %forexit.0
forbody.0:
  %t8 = load i32, ptr %outIndex
  %t9 = add i32 0, 8
  %t10 = icmp eq i32 %t8, %t9
  %t11 = zext i1 %t10 to i32
  %t12 = load i32, ptr %outIndex
  %t13 = add i32 0, 13
  %t14 = icmp eq i32 %t12, %t13
  %t15 = zext i1 %t14 to i32
  %t16 = or i32 %t11, %t15
  %t17 = load i32, ptr %outIndex
  %t18 = add i32 0, 18
  %t19 = icmp eq i32 %t17, %t18
  %t20 = zext i1 %t19 to i32
  %t21 = or i32 %t16, %t20
  %t22 = load i32, ptr %outIndex
  %t23 = add i32 0, 23
  %t24 = icmp eq i32 %t22, %t23
  %t25 = zext i1 %t24 to i32
  %t26 = or i32 %t21, %t25
  %t27 = icmp ne i32 %t26, 0
  br i1 %t27, label %then.1, label %merge.1
then.1:
  %t28 = load i32, ptr %outIndex
  %t29 = sub i32 %t28, 1
  store i32 %t29, ptr %outIndex
  br label %merge.1
merge.1:
  %t30 = load ptr, ptr @pool
  %t31 = load i32, ptr @poolOffset
  %t32 = sub i32 %t31, 1
  store i32 %t32, ptr @poolOffset
  %t33 = getelementptr i32, ptr %t30, i32 %t32
  %t34 = load i32, ptr %t33
  store i32 %t34, ptr %_byte
  %t35 = load i32, ptr %i
  %t36 = add i32 0, 6
  %t37 = icmp eq i32 %t35, %t36
  %t38 = zext i1 %t37 to i32
  %t39 = icmp ne i32 %t38, 0
  br i1 %t39, label %then.2, label %else.2
then.2:
  %t40 = load i32, ptr %_byte
  %t41 = add i32 0, 15
  %t42 = and i32 %t40, %t41
  %t43 = add i32 0, 64
  %t44 = or i32 %t42, %t43
  store i32 %t44, ptr %_byte
  br label %merge.2
else.2:
  %t45 = load i32, ptr %i
  %t46 = add i32 0, 8
  %t47 = icmp eq i32 %t45, %t46
  %t48 = zext i1 %t47 to i32
  %t49 = icmp ne i32 %t48, 0
  br i1 %t49, label %then.3, label %merge.3
then.3:
  %t50 = load i32, ptr %_byte
  %t51 = add i32 0, 63
  %t52 = and i32 %t50, %t51
  %t53 = add i32 0, 128
  %t54 = or i32 %t52, %t53
  store i32 %t54, ptr %_byte
  br label %merge.3
merge.3:
  br label %merge.2
merge.2:
  %t55 = load ptr, ptr @hexLookup
  %t56 = load i32, ptr %_byte
  %t57 = add i32 0, 4
  %t58 = ashr i32 %t56, %t57
  %t59 = getelementptr i32, ptr %t55, i32 %t58
  %t60 = load i32, ptr %t59
  %t61 = load ptr, ptr @outBuffer
  %t62 = load i32, ptr %outIndex
  %t63 = sub i32 %t62, 1
  store i32 %t63, ptr %outIndex
  %t64 = getelementptr i32, ptr %t61, i32 %t63
  store i32 %t60, ptr %t64
  %t65 = load ptr, ptr @hexLookup
  %t66 = load i32, ptr %_byte
  %t67 = add i32 0, 15
  %t68 = and i32 %t66, %t67
  %t69 = getelementptr i32, ptr %t65, i32 %t68
  %t70 = load i32, ptr %t69
  %t71 = load ptr, ptr @outBuffer
  %t72 = load i32, ptr %outIndex
  %t73 = sub i32 %t72, 1
  store i32 %t73, ptr %outIndex
  %t74 = getelementptr i32, ptr %t71, i32 %t73
  store i32 %t70, ptr %t74
  br label %forupdate.0
forupdate.0:
  %t75 = load i32, ptr %i
  %t76 = sub i32 %t75, 1
  store i32 %t76, ptr %i
  br label %for.0
forexit.0:
  %t77 = load i32, ptr @outBuffer
  ret i32 %t77
  ret i32 0
}

define i32 @generateUUIDv4Raw() {
entry:
  %i = alloca i32
  %_byte2 = alloca i32
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t0 = add i32 0, 0
  %t1 = add i32 0, 0
  store i32 %t1, ptr %i
  br label %for.0
for.0:
  %t2 = load i32, ptr %i
  %t3 = add i32 0, 16
  %t4 = icmp slt i32 %t2, %t3
  %t5 = zext i1 %t4 to i32
  %t6 = icmp ne i32 %t5, 0
  br i1 %t6, label %forbody.0, label %forexit.0
forbody.0:
  %t7 = load ptr, ptr @pool
  %t8 = load i32, ptr @poolOffset
  %t9 = sub i32 %t8, 1
  store i32 %t9, ptr @poolOffset
  %t10 = getelementptr i32, ptr %t7, i32 %t9
  %t11 = load i32, ptr %t10
  store i32 %t11, ptr %_byte2
  %t12 = load i32, ptr %i
  %t13 = add i32 0, 6
  %t14 = icmp eq i32 %t12, %t13
  %t15 = zext i1 %t14 to i32
  %t16 = icmp ne i32 %t15, 0
  br i1 %t16, label %then.1, label %else.1
then.1:
  %t17 = load i32, ptr %_byte2
  %t18 = add i32 0, 15
  %t19 = and i32 %t17, %t18
  %t20 = add i32 0, 64
  %t21 = or i32 %t19, %t20
  store i32 %t21, ptr %_byte2
  br label %merge.1
else.1:
  %t22 = load i32, ptr %i
  %t23 = add i32 0, 8
  %t24 = icmp eq i32 %t22, %t23
  %t25 = zext i1 %t24 to i32
  %t26 = icmp ne i32 %t25, 0
  br i1 %t26, label %then.2, label %merge.2
then.2:
  %t27 = load i32, ptr %_byte2
  %t28 = add i32 0, 63
  %t29 = and i32 %t27, %t28
  %t30 = add i32 0, 128
  %t31 = or i32 %t29, %t30
  store i32 %t31, ptr %_byte2
  br label %merge.2
merge.2:
  br label %merge.1
merge.1:
  %t32 = load i32, ptr %_byte2
  %t33 = load ptr, ptr @rawBuffer
  %t34 = load i32, ptr %i
  %t35 = getelementptr i32, ptr %t33, i32 %t34
  store i32 %t32, ptr %t35
  br label %forupdate.0
forupdate.0:
  %t36 = load i32, ptr %i
  %t37 = sub i32 %t36, 1
  store i32 %t37, ptr %i
  br label %for.0
forexit.0:
  %t38 = load i32, ptr @rawBuffer
  ret i32 %t38
  ret i32 0
}

