; Ohnrscript LLVM IR Backend
; generated by generator-llvm.ohn

declare ptr @ohn_alloc_f32(i32)
declare void @ohn_free(ptr)

@ohn_ws_initialized = global i1 0
@ohn_ws_exports = global ptr null

define ptr @__get_module_exports_ohn_ws() {
entry:
  %init_flag = load i1, ptr @ohn_ws_initialized
  br i1 %init_flag, label %return_block, label %init_block
init_block:
  store i1 1, ptr @ohn_ws_initialized
  ; (module.exports skipped — handled by lazy gett  store ptr null, ptr @ohn_ws_exports
  br label %return_block
return_block:
  %exports_val = load ptr, ptr @ohn_ws_exports
  ret ptr %exports_val
}

define i32 @parseFrame(i64 %buffer) {
entry:
  %byte0 = alloca i32
  %byte1 = alloca i32
  %fin = alloca i32
  %opcode = alloca i32
  %masked = alloca i32
  %payloadLength = alloca i32
  %offset = alloca i32
  %high = alloca i32
  %low = alloca i32
  %maskKey = alloca i32
  %payloadStart = alloca i32
  %i = alloca i32
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t0 = add i32 0, 0
  %t1 = add i32 0, 2
  %t2 = icmp slt i32 %t0, %t1
  %t3 = zext i1 %t2 to i32
  %t4 = icmp ne i32 %t3, 0
  br i1 %t4, label %then.0, label %merge.0
then.0:
  %t5 = add i32 0, 0
  ret i32 %t5
  br label %merge.0
merge.0:
  %t6 = inttoptr i64 %buffer to ptr
  %t7 = add i32 0, 0
  %t8 = getelementptr i32, ptr %t6, i32 %t7
  %t9 = load i32, ptr %t8
  store i32 %t9, ptr %byte0
  %t10 = inttoptr i64 %buffer to ptr
  %t11 = add i32 0, 1
  %t12 = getelementptr i32, ptr %t10, i32 %t11
  %t13 = load i32, ptr %t12
  store i32 %t13, ptr %byte1
  %t14 = load i32, ptr %byte0
  %t15 = add i32 0, 128
  %t16 = and i32 %t14, %t15
  %t17 = add i32 0, 128
  %t18 = icmp eq i32 %t16, %t17
  %t19 = zext i1 %t18 to i32
  store i32 %t19, ptr %fin
  %t20 = load i32, ptr %byte0
  %t21 = add i32 0, 15
  %t22 = and i32 %t20, %t21
  store i32 %t22, ptr %opcode
  %t23 = load i32, ptr %byte1
  %t24 = add i32 0, 128
  %t25 = and i32 %t23, %t24
  %t26 = add i32 0, 128
  %t27 = icmp eq i32 %t25, %t26
  %t28 = zext i1 %t27 to i32
  store i32 %t28, ptr %masked
  %t29 = load i32, ptr %byte1
  %t30 = add i32 0, 127
  %t31 = and i32 %t29, %t30
  store i32 %t31, ptr %payloadLength
  %t32 = add i32 0, 2
  store i32 %t32, ptr %offset
  %t33 = load i32, ptr %payloadLength
  %t34 = add i32 0, 126
  %t35 = icmp eq i32 %t33, %t34
  %t36 = zext i1 %t35 to i32
  %t37 = icmp ne i32 %t36, 0
  br i1 %t37, label %then.1, label %else.1
then.1:
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t38 = add i32 0, 0
  %t39 = add i32 0, 4
  %t40 = icmp slt i32 %t38, %t39
  %t41 = zext i1 %t40 to i32
  %t42 = icmp ne i32 %t41, 0
  br i1 %t42, label %then.2, label %merge.2
then.2:
  %t43 = add i32 0, 0
  ret i32 %t43
  br label %merge.2
merge.2:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t44 = add i32 0, 0
  store i32 %t44, ptr %payloadLength
  %t45 = add i32 0, 2
  store i32 %t45, ptr %offset
  br label %merge.1
else.1:
  %t46 = load i32, ptr %payloadLength
  %t47 = add i32 0, 127
  %t48 = icmp eq i32 %t46, %t47
  %t49 = zext i1 %t48 to i32
  %t50 = icmp ne i32 %t49, 0
  br i1 %t50, label %then.3, label %merge.3
then.3:
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t51 = add i32 0, 0
  %t52 = add i32 0, 10
  %t53 = icmp slt i32 %t51, %t52
  %t54 = zext i1 %t53 to i32
  %t55 = icmp ne i32 %t54, 0
  br i1 %t55, label %then.4, label %merge.4
then.4:
  %t56 = add i32 0, 0
  ret i32 %t56
  br label %merge.4
merge.4:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t57 = add i32 0, 0
  store i32 %t57, ptr %high
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t58 = add i32 0, 0
  store i32 %t58, ptr %low
  %t59 = load i32, ptr %high
  %t60 = add i32 0, 0
  %t61 = mul i32 %t59, %t60
  %t62 = load i32, ptr %low
  %t63 = add i32 %t61, %t62
  store i32 %t63, ptr %payloadLength
  %t64 = add i32 0, 8
  store i32 %t64, ptr %offset
  br label %merge.3
merge.3:
  br label %merge.1
merge.1:
  %t65 = load i32, ptr %masked
  %t66 = icmp ne i32 %t65, 0
  br i1 %t66, label %then.5, label %merge.5
then.5:
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t67 = add i32 0, 0
  %t68 = load i32, ptr %offset
  %t69 = add i32 0, 4
  %t70 = add i32 %t68, %t69
  %t71 = icmp slt i32 %t67, %t70
  %t72 = zext i1 %t71 to i32
  %t73 = icmp ne i32 %t72, 0
  br i1 %t73, label %then.6, label %merge.6
then.6:
  %t74 = add i32 0, 0
  ret i32 %t74
  br label %merge.6
merge.6:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t75 = add i32 0, 0
  store i32 %t75, ptr %maskKey
  %t76 = add i32 0, 4
  store i32 %t76, ptr %offset
  br label %merge.5
merge.5:
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t77 = add i32 0, 0
  %t78 = load i32, ptr %offset
  %t79 = load i32, ptr %payloadLength
  %t80 = add i32 %t78, %t79
  %t81 = icmp slt i32 %t77, %t80
  %t82 = zext i1 %t81 to i32
  %t83 = icmp ne i32 %t82, 0
  br i1 %t83, label %then.7, label %merge.7
then.7:
  %t84 = add i32 0, 0
  ret i32 %t84
  br label %merge.7
merge.7:
  %t85 = load i32, ptr %offset
  store i32 %t85, ptr %payloadStart
  %t86 = load i32, ptr %masked
  %t87 = load i32, ptr %payloadLength
  %t88 = add i32 0, 0
  %t89 = icmp sgt i32 %t87, %t88
  %t90 = zext i1 %t89 to i32
  %t91 = and i32 %t86, %t90
  %t92 = icmp ne i32 %t91, 0
  br i1 %t92, label %then.8, label %merge.8
then.8:
  %t93 = add i32 0, 0
  store i32 %t93, ptr %i
  br label %for.9
for.9:
  %t94 = load i32, ptr %i
  %t95 = load i32, ptr %payloadLength
  %t96 = icmp slt i32 %t94, %t95
  %t97 = zext i1 %t96 to i32
  %t98 = icmp ne i32 %t97, 0
  br i1 %t98, label %forbody.9, label %forexit.9
forbody.9:
  %t99 = load ptr, ptr %maskKey
  %t100 = load i32, ptr %i
  %t101 = add i32 0, 3
  %t102 = and i32 %t100, %t101
  %t103 = getelementptr i32, ptr %t99, i32 %t102
  %t104 = load i32, ptr %t103
  %t105 = inttoptr i64 %buffer to ptr
  %t106 = load i32, ptr %payloadStart
  %t107 = load i32, ptr %i
  %t108 = add i32 %t106, %t107
  %t109 = getelementptr i32, ptr %t105, i32 %t108
  store i32 %t104, ptr %t109
  br label %forupdate.9
forupdate.9:
  %t110 = load i32, ptr %i
  %t111 = sub i32 %t110, 1
  store i32 %t111, ptr %i
  br label %for.9
forexit.9:
  br label %merge.8
merge.8:
  ; UNSUPPORTED node type: 0x17
  %t112 = add i32 0, 0
  ret i32 %t112
  ret i32 0
}

