; Ohnrscript LLVM IR Backend
; generated by generator-llvm.ohn

declare ptr @ohn_alloc_f32(i32)
declare void @ohn_free(ptr)

@ohn_cookie_initialized = global i1 0
@ohn_cookie_exports = global ptr null

define ptr @__get_module_exports_ohn_cookie() {
entry:
  %init_flag = load i1, ptr @ohn_cookie_initialized
  br i1 %init_flag, label %return_block, label %init_block
init_block:
  store i1 1, ptr @ohn_cookie_initialized
  ; (module.exports skipped — handled by lazy gett  store ptr null, ptr @ohn_cookie_exports
  br label %return_block
return_block:
  %exports_val = load ptr, ptr @ohn_cookie_exports
  ret ptr %exports_val
}

define i32 @scanCookies(i64 %buffer) {
entry:
  %results = alloca i32
  %len = alloca i32
  %i = alloca i32
  %keyStart = alloca i32
  %keyEnd = alloca i32
  %valStart = alloca i32
  %valEnd = alloca i32
  ; UNSUPPORTED node type: 0xe
  %t0 = add i32 0, 0
  store i32 %t0, ptr %results
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t1 = add i32 0, 0
  store i32 %t1, ptr %len
  %t2 = add i32 0, 0
  store i32 %t2, ptr %i
  br label %loop.0
loop.0:
  %t3 = load i32, ptr %i
  %t4 = load i32, ptr %len
  %t5 = icmp slt i32 %t3, %t4
  %t6 = zext i1 %t5 to i32
  %t7 = icmp ne i32 %t6, 0
  br i1 %t7, label %body.0, label %exit.0
body.0:
  br label %loop.1
loop.1:
  %t8 = load i32, ptr %i
  %t9 = load i32, ptr %len
  %t10 = icmp slt i32 %t8, %t9
  %t11 = zext i1 %t10 to i32
  %t12 = inttoptr i64 %buffer to ptr
  %t13 = load i32, ptr %i
  %t14 = getelementptr i32, ptr %t12, i32 %t13
  %t15 = load i32, ptr %t14
  %t16 = add i32 0, 32
  %t17 = icmp eq i32 %t15, %t16
  %t18 = zext i1 %t17 to i32
  %t19 = and i32 %t11, %t18
  %t20 = icmp ne i32 %t19, 0
  br i1 %t20, label %body.1, label %exit.1
body.1:
  %t21 = load i32, ptr %i
  %t22 = sub i32 %t21, 1
  store i32 %t22, ptr %i
  br label %loop.1
exit.1:
  %t23 = load i32, ptr %i
  %t24 = load i32, ptr %len
  %t25 = icmp sge i32 %t23, %t24
  %t26 = zext i1 %t25 to i32
  %t27 = icmp ne i32 %t26, 0
  br i1 %t27, label %then.2, label %merge.2
then.2:
  ; UNSUPPORTED node type: 0x12
  %t28 = add i32 0, 0
  br label %merge.2
merge.2:
  %t29 = load i32, ptr %i
  store i32 %t29, ptr %keyStart
  br label %loop.3
loop.3:
  %t30 = load i32, ptr %i
  %t31 = load i32, ptr %len
  %t32 = icmp slt i32 %t30, %t31
  %t33 = zext i1 %t32 to i32
  %t34 = inttoptr i64 %buffer to ptr
  %t35 = load i32, ptr %i
  %t36 = getelementptr i32, ptr %t34, i32 %t35
  %t37 = load i32, ptr %t36
  %t38 = add i32 0, 61
  %t39 = icmp ne i32 %t37, %t38
  %t40 = zext i1 %t39 to i32
  %t41 = and i32 %t33, %t40
  %t42 = inttoptr i64 %buffer to ptr
  %t43 = load i32, ptr %i
  %t44 = getelementptr i32, ptr %t42, i32 %t43
  %t45 = load i32, ptr %t44
  %t46 = add i32 0, 59
  %t47 = icmp ne i32 %t45, %t46
  %t48 = zext i1 %t47 to i32
  %t49 = and i32 %t41, %t48
  %t50 = icmp ne i32 %t49, 0
  br i1 %t50, label %body.3, label %exit.3
body.3:
  %t51 = load i32, ptr %i
  %t52 = sub i32 %t51, 1
  store i32 %t52, ptr %i
  br label %loop.3
exit.3:
  %t53 = load i32, ptr %i
  store i32 %t53, ptr %keyEnd
  br label %loop.4
loop.4:
  %t54 = load i32, ptr %keyEnd
  %t55 = load i32, ptr %keyStart
  %t56 = icmp sgt i32 %t54, %t55
  %t57 = zext i1 %t56 to i32
  %t58 = inttoptr i64 %buffer to ptr
  %t59 = load i32, ptr %keyEnd
  %t60 = add i32 0, 1
  %t61 = sub i32 %t59, %t60
  %t62 = getelementptr i32, ptr %t58, i32 %t61
  %t63 = load i32, ptr %t62
  %t64 = add i32 0, 32
  %t65 = icmp eq i32 %t63, %t64
  %t66 = zext i1 %t65 to i32
  %t67 = and i32 %t57, %t66
  %t68 = icmp ne i32 %t67, 0
  br i1 %t68, label %body.4, label %exit.4
body.4:
  %t69 = load i32, ptr %keyEnd
  %t70 = sub i32 %t69, 1
  store i32 %t70, ptr %keyEnd
  br label %loop.4
exit.4:
  ; UNSUPPORTED node type: 0xf
  %t71 = add i32 0, 0
  store i32 %t71, ptr %valStart
  ; UNSUPPORTED node type: 0xf
  %t72 = add i32 0, 0
  store i32 %t72, ptr %valEnd
  %t73 = load i32, ptr %i
  %t74 = load i32, ptr %len
  %t75 = icmp slt i32 %t73, %t74
  %t76 = zext i1 %t75 to i32
  %t77 = inttoptr i64 %buffer to ptr
  %t78 = load i32, ptr %i
  %t79 = getelementptr i32, ptr %t77, i32 %t78
  %t80 = load i32, ptr %t79
  %t81 = add i32 0, 61
  %t82 = icmp eq i32 %t80, %t81
  %t83 = zext i1 %t82 to i32
  %t84 = and i32 %t76, %t83
  %t85 = icmp ne i32 %t84, 0
  br i1 %t85, label %then.5, label %else.5
then.5:
  %t86 = load i32, ptr %i
  %t87 = sub i32 %t86, 1
  store i32 %t87, ptr %i
  br label %loop.6
loop.6:
  %t88 = load i32, ptr %i
  %t89 = load i32, ptr %len
  %t90 = icmp slt i32 %t88, %t89
  %t91 = zext i1 %t90 to i32
  %t92 = inttoptr i64 %buffer to ptr
  %t93 = load i32, ptr %i
  %t94 = getelementptr i32, ptr %t92, i32 %t93
  %t95 = load i32, ptr %t94
  %t96 = add i32 0, 32
  %t97 = icmp eq i32 %t95, %t96
  %t98 = zext i1 %t97 to i32
  %t99 = and i32 %t91, %t98
  %t100 = icmp ne i32 %t99, 0
  br i1 %t100, label %body.6, label %exit.6
body.6:
  %t101 = load i32, ptr %i
  %t102 = sub i32 %t101, 1
  store i32 %t102, ptr %i
  br label %loop.6
exit.6:
  %t103 = load i32, ptr %i
  store i32 %t103, ptr %valStart
  br label %loop.7
loop.7:
  %t104 = load i32, ptr %i
  %t105 = load i32, ptr %len
  %t106 = icmp slt i32 %t104, %t105
  %t107 = zext i1 %t106 to i32
  %t108 = inttoptr i64 %buffer to ptr
  %t109 = load i32, ptr %i
  %t110 = getelementptr i32, ptr %t108, i32 %t109
  %t111 = load i32, ptr %t110
  %t112 = add i32 0, 59
  %t113 = icmp ne i32 %t111, %t112
  %t114 = zext i1 %t113 to i32
  %t115 = and i32 %t107, %t114
  %t116 = icmp ne i32 %t115, 0
  br i1 %t116, label %body.7, label %exit.7
body.7:
  %t117 = load i32, ptr %i
  %t118 = sub i32 %t117, 1
  store i32 %t118, ptr %i
  br label %loop.7
exit.7:
  %t119 = load i32, ptr %i
  store i32 %t119, ptr %valEnd
  br label %loop.8
loop.8:
  %t120 = load i32, ptr %valEnd
  %t121 = load i32, ptr %valStart
  %t122 = icmp sgt i32 %t120, %t121
  %t123 = zext i1 %t122 to i32
  %t124 = inttoptr i64 %buffer to ptr
  %t125 = load i32, ptr %valEnd
  %t126 = add i32 0, 1
  %t127 = sub i32 %t125, %t126
  %t128 = getelementptr i32, ptr %t124, i32 %t127
  %t129 = load i32, ptr %t128
  %t130 = add i32 0, 32
  %t131 = icmp eq i32 %t129, %t130
  %t132 = zext i1 %t131 to i32
  %t133 = and i32 %t123, %t132
  %t134 = icmp ne i32 %t133, 0
  br i1 %t134, label %body.8, label %exit.8
body.8:
  %t135 = load i32, ptr %valEnd
  %t136 = sub i32 %t135, 1
  store i32 %t136, ptr %valEnd
  br label %loop.8
exit.8:
  br label %merge.5
else.5:
  %t137 = load i32, ptr %keyEnd
  store i32 %t137, ptr %valStart
  %t138 = load i32, ptr %keyEnd
  store i32 %t138, ptr %valEnd
  br label %merge.5
merge.5:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t139 = add i32 0, 0
  %t140 = load i32, ptr %i
  %t141 = load i32, ptr %len
  %t142 = icmp slt i32 %t140, %t141
  %t143 = zext i1 %t142 to i32
  %t144 = inttoptr i64 %buffer to ptr
  %t145 = load i32, ptr %i
  %t146 = getelementptr i32, ptr %t144, i32 %t145
  %t147 = load i32, ptr %t146
  %t148 = add i32 0, 59
  %t149 = icmp eq i32 %t147, %t148
  %t150 = zext i1 %t149 to i32
  %t151 = and i32 %t143, %t150
  %t152 = icmp ne i32 %t151, 0
  br i1 %t152, label %then.9, label %merge.9
then.9:
  %t153 = load i32, ptr %i
  %t154 = sub i32 %t153, 1
  store i32 %t154, ptr %i
  br label %merge.9
merge.9:
  br label %loop.0
exit.0:
  %t155 = load i32, ptr %results
  ret i32 %t155
  ret i32 0
}

define i32 @getCookie(i64 %headerBuffer, i64 %keyString) {
entry:
  %pointers = alloca i32
  %keyBuf = alloca i32
  %keyLen = alloca i32
  %i = alloca i32
  %p = alloca i32
  %matchLen = alloca i32
  %isMatch = alloca i32
  %j = alloca i32
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t0 = add i32 0, 0
  store i32 %t0, ptr %pointers
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t1 = add i32 0, 0
  store i32 %t1, ptr %keyBuf
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t2 = add i32 0, 0
  store i32 %t2, ptr %keyLen
  %t3 = add i32 0, 0
  store i32 %t3, ptr %i
  br label %for.0
for.0:
  %t4 = load i32, ptr %i
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t5 = add i32 0, 0
  %t6 = icmp slt i32 %t4, %t5
  %t7 = zext i1 %t6 to i32
  %t8 = icmp ne i32 %t7, 0
  br i1 %t8, label %forbody.0, label %forexit.0
forbody.0:
  %t9 = load ptr, ptr %pointers
  %t10 = load i32, ptr %i
  %t11 = getelementptr i32, ptr %t9, i32 %t10
  %t12 = load i32, ptr %t11
  store i32 %t12, ptr %p
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t13 = add i32 0, 0
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t14 = add i32 0, 0
  %t15 = sub i32 %t13, %t14
  store i32 %t15, ptr %matchLen
  %t16 = load i32, ptr %matchLen
  %t17 = load i32, ptr %keyLen
  %t18 = icmp eq i32 %t16, %t17
  %t19 = zext i1 %t18 to i32
  %t20 = icmp ne i32 %t19, 0
  br i1 %t20, label %then.1, label %merge.1
then.1:
  %t21 = add i32 0, 1
  store i32 %t21, ptr %isMatch
  %t22 = add i32 0, 0
  store i32 %t22, ptr %j
  br label %for.2
for.2:
  %t23 = load i32, ptr %j
  %t24 = load i32, ptr %keyLen
  %t25 = icmp slt i32 %t23, %t24
  %t26 = zext i1 %t25 to i32
  %t27 = icmp ne i32 %t26, 0
  br i1 %t27, label %forbody.2, label %forexit.2
forbody.2:
  %t28 = inttoptr i64 %headerBuffer to ptr
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t29 = add i32 0, 0
  %t30 = load i32, ptr %j
  %t31 = add i32 %t29, %t30
  %t32 = getelementptr i32, ptr %t28, i32 %t31
  %t33 = load i32, ptr %t32
  %t34 = load ptr, ptr %keyBuf
  %t35 = load i32, ptr %j
  %t36 = getelementptr i32, ptr %t34, i32 %t35
  %t37 = load i32, ptr %t36
  %t38 = icmp ne i32 %t33, %t37
  %t39 = zext i1 %t38 to i32
  %t40 = icmp ne i32 %t39, 0
  br i1 %t40, label %then.3, label %merge.3
then.3:
  %t41 = add i32 0, 0
  store i32 %t41, ptr %isMatch
  ; UNSUPPORTED node type: 0x12
  %t42 = add i32 0, 0
  br label %merge.3
merge.3:
  br label %forupdate.2
forupdate.2:
  %t43 = load i32, ptr %j
  %t44 = sub i32 %t43, 1
  store i32 %t44, ptr %j
  br label %for.2
forexit.2:
  %t45 = load i32, ptr %isMatch
  %t46 = icmp ne i32 %t45, 0
  br i1 %t46, label %then.4, label %merge.4
then.4:
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t47 = add i32 0, 0
  ; UNSUPPORTED node type: 0x7 (non-computed member)
  %t48 = add i32 0, 0
  %t49 = icmp eq i32 %t47, %t48
  %t50 = zext i1 %t49 to i32
  %t51 = icmp ne i32 %t50, 0
  br i1 %t51, label %then.5, label %merge.5
then.5:
  %t52 = add i32 0, 0
  ret i32 %t52
  br label %merge.5
merge.5:
  ; UNSUPPORTED node type: 0x5 (call expression)
  %t53 = add i32 0, 0
  ret i32 %t53
  br label %merge.4
merge.4:
  br label %merge.1
merge.1:
  br label %forupdate.0
forupdate.0:
  %t54 = load i32, ptr %i
  %t55 = sub i32 %t54, 1
  store i32 %t55, ptr %i
  br label %for.0
forexit.0:
  %t56 = add i32 0, 0
  ret i32 %t56
  ret i32 0
}

