; Ohnrscript LLVM IR Backend
; generated by generator-llvm.ohn

declare ptr @ohn_alloc_f32(i32)
declare void @ohn_free(ptr)

@keyboard_initialized = global i1 0
@keyboard_exports = global ptr null
@inb = global i32 0

define ptr @__get_module_exports_keyboard() {
entry:
  %init_flag = load i1, ptr @keyboard_initialized
  br i1 %init_flag, label %return_block, label %init_block
init_block:
  store i1 1, ptr @keyboard_initialized
  %t0 = add i32 0, 96
  %t1 = zext i32 %t0 to i64
  %t2 = call i32 @processKeystroke(i64 %t1)
  store ptr null, ptr @keyboard_exports
  br label %return_block
return_block:
  %exports_val = load ptr, ptr @keyboard_exports
  ret ptr %exports_val
}

define i32 @processKeystroke(i64 %port) {
entry:
  %result = alloca i32
  %t0 = add i32 0, 0
  store i32 %t0, ptr %result
  br label %loop.0
loop.0:
  %t1 = add i32 0, 1
  %t2 = icmp ne i32 %t1, 0
  br i1 %t2, label %body.0, label %exit.0
body.0:
  %t3 = trunc i64 %port to i32
  %t4 = call i64 @inb(i32 %t3)
  %t5 = trunc i64 %t4 to i32
  store i32 %t5, ptr %result
  %t6 = load i32, ptr %result
  %t7 = add i32 0, 0
  %t8 = icmp ne i32 %t6, %t7
  %t9 = zext i1 %t8 to i32
  %t10 = icmp ne i32 %t9, 0
  br i1 %t10, label %then.1, label %merge.1
then.1:
  br label %exit.0
  br label %merge.1
merge.1:
  br label %loop.0
exit.0:
  %t11 = load i32, ptr %result
  ret i32 %t11
  ret i32 0
}

declare i64 @inb(...)
